---
# tasks file for enable-sleep
- name: Enable sleep
  become: true
  ansible.builtin.systemd:
    masked: false
    name: "{{ item }}"
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target
    - suspend-then-hibernate.target
  changed_when: false
