---
# handlers file for nvidia
- name: Run akmods
  become: true
  ansible.builtin.command: /usr/sbin/akmods --rebuild
- name: Run dracut
  become: true
  ansible.builtin.command: /usr/bin/dracut --force
